spring:
  cloud:
    consul:
      host: localhost
  zipkin:
    base-url: http://localhost:9411

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8080/auth/oauth/token_key
