spring:
  cloud:
    consul:
      host: localhost
  zipkin:
    base-url: http://localhost:9411

security:
  oauth2:
    client:
      client-id: service1
      client-secret: secret
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
      scope: all
  resource:
    jwt:
      key-uri: http://localhost:8080/auth/oauth/token_key
    token-info-uri: http://localhost:8080/auth/oauth/check_token
